Portifolio
Jessekay/Portifolio pull request #2
Opened 2023-01-12 09:18 UTC by Jessekay

portifolio(mobile version)

2023-01-12 10:43 UTC, Owusu-Desmond requested changes
Hi @Jessekay , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/KpUmECkP8UDX4L7SkU/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 I like your design ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

- [ ] I can't use the inline comments for the following code but you have the below code in your `index.html`.

  ```html
  <div class="menu">
      <div class="logo">My Logo</div>
      <nav><img src="./images/ham.svg" alt=""></nav>
      </div>
      <main>
  ```
    - Please make sure that you use the `header` for the `<div class="menu">` instead of the `div` for semantic reasons. Typically the header tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.
    - Please make sure that the logo has a link (`a` tag). This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

- [ ] I can't also use the inline comments for the following code but you have the below code in your `index.html`.
  ```html
  <div class="bg-image">
          <div class="wrapper1">
  
          <div class="text"><h2>Hey am Jesse <br>Glad to see<br> you!</h2></div>
      <div class="txt">I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded, don’t hestiate to contact me.</div><br>
      <div class="tx">LET'S CONNECT</div><br>
      <div class="socials">
          <ul>
              <img src="./images/twitter.png" alt="">
              <li><a href=""></a></li>
              <img src="./images/linkedin.png" alt="">
              <li><a href=""></a></li>
              <img src="./images/m.png" alt="">
              <li><a href=""></a></li>
              <img src="./images/github.png" alt="">
              <li><a href=""></a></li>
              <img src="./images/bak.png" alt="">
              <li><a href=""></a></li>
          </ul>
      </div>
      </div>
  ```
  - Please make sure that you use the `section` tag for `<div class="bg-image">`. It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info
  - Please make sure the main title (e.g., "I'm Marianne ...") is an `h1` tag. This will help so that If you want that google (and other search engines) know about a specific topic, in this case, you, use an `h1` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.
  - Why don't you use `p` tag for the `I’m a software developer! I can ..`.
  - Please make sure that your social media list is in a form of 
    ```html
      <ul>
            <li><a href=""><img src="./images/twitter.png" alt=""></a></li>
            <!-- others links here -->
        </ul>
    ```
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 12:21 UTC, Favourezeugwa requested changes
## STATUS: REQUIRES CHANGES 🚦 ⚠️ ♻️ 

Hi @Jessekay  , 

Great job implementing some of the required changes suggested by the previous reviewer. 
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-brianna](https://user-images.githubusercontent.com/99246359/201470450-173d4ea7-fe78-470e-a872-142a58b56294.gif)


## Highlights 💯 
- No Linter errors ✔️
- Descriptive Pull request summary✔️
- Good commit messages ✔️
- Professional Readme file ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 12:21 UTC, Favourezeugwa commented on index.html
> +        <link class="logo">My Logo</link>
- I think it will be better to wrap your `My Logo` in an `<a>` tag since it is a clickable link. This is usually for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info

- I'd like to kindly suggest that you can personalize the text `My logo` to somethng that defines you. Maybe your firstname or nickname will be just fine 🌸

2023-01-12 12:21 UTC, Favourezeugwa commented on index.html
>      <div class="tx">LET'S CONNECT</div><br>
- Just as the previous reviewer suggested, kindly use or add  `<p>` tag for the `I’m a software developer! I can ...`. This way will be semantically correct and the screen readers and other technologies will thank you.

- I believe the `LET'S CONNECT` is meant to be a button or an anchor tag. Can we kindly add either of them because it is a clickable link? 🤗

2023-01-12 12:21 UTC, Favourezeugwa commented on README.md
> +
- Just as the readme says, Kindly include some key features of your project. It is good to use a readme template, but it is important to PERSONALIZE it as much as possible. 👍🏽

2023-01-12 12:21 UTC, Favourezeugwa commented on README.md
> +
- I believe it is important to include steps on how to set up, use, and install your portfolio locally on a user's machine. Can you kindly include those steps? 🤗

2023-01-12 13:44 UTC, frank1738 requested changes
Hi @Jessekay , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>


## Highlights

✅ Correct use of Github workflow
✅ No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 13:44 UTC, frank1738 commented on index.html
> +
- [ ] Good work on adjusting your logo but also I would like to suggest that you style it i.e  make it bold and adjust the color to match the Figma design

![image](https://user-images.githubusercontent.com/98453979/212078825-7b7bb5ec-3846-4edd-ba26-9d09b977b764.png)

### Checkout the original design

![image](https://user-images.githubusercontent.com/98453979/212079091-8d0003b7-c25b-4b22-982b-1e0182baa14e.png)

2023-01-12 13:44 UTC, frank1738 commented on index.html
> +    <link class="tx">LET'S CONNECT</link><br>
- [ ] The same applies to the `lets's connect ` link. Kindly style it and position it correctly to match the original design

![image](https://user-images.githubusercontent.com/98453979/212079797-8015dd3f-ff69-4f8c-a3c5-6202b4182670.png)

### Checkout  the original design

![image](https://user-images.githubusercontent.com/98453979/212080778-29e3c60e-77eb-4bda-b268-7a7aff691051.png)

2023-01-12 13:44 UTC, frank1738 commented on README.md
> +## 🛠 Built With <a name="built-with"></a>
- [ ] As suggested earlier, Kindly adjust the title of your project as you are now currently working on the Portfolio. Also, be sure to include the `key features` and the `future features` of your project.

2023-01-12 19:48 UTC, vickymarz requested changes
Hi @Jessekay, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- **I will strongly recommend you always implement suggested changes by code reviewers on your project. THe essence of code review is to improve your coding skills. So please always implement all required changes before submitting again. You can also always reach out for help if anything is not clear to you 👍🏽** 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 19:48 UTC, vickymarz commented on index.html
> +    <header class="menu">
- [ ] I think it will be better if you implement this changes suggested by the previous reviewer 👇🏽 

![image](https://user-images.githubusercontent.com/63473584/212165131-4c3f562f-ae8b-4577-861e-ed7ff62c6fa9.png)

2023-01-12 19:48 UTC, vickymarz commented on index.html
> +    <link class="tx">LET'S CONNECT</link><br>
- [ ] KIndly implement this changes suggested by the previous reviewer 👇🏽 

![image](https://user-images.githubusercontent.com/63473584/212165354-66d0cc9a-657c-4ded-832f-58400f35d75f.png)

2023-01-12 19:48 UTC, vickymarz commented on README.md
> +## 🛠 Built With <a name="built-with"></a>
- [ ] KIndly implement the changes suggested by the previous reviewer 👇🏽 

![image](https://user-images.githubusercontent.com/63473584/212165760-bdd2f2db-3b48-4e30-b977-87379c6e6449.png)

2023-01-12 19:59 UTC, Jessekay commented
Thats what I have done may be you can review again please

On Thu, Jan 12, 2023 at 9:48 PM Victor Ebube Okoroji <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Jessekay <https://github.com/Jessekay>,
>
> Great work on making the changes requested by a previous reviewer 👏 🔥
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
>
>
> <https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966>
> Top highlight 🎯
>
>    - The PR title and description are professional and descriptive ✅
>    - Linters are working properly ✅
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
>    - *I will strongly recommend you always implement suggested changes by
>    code reviewers on your project. THe essence of code review is to improve
>    your coding skills. So please always implement all required changes before
>    submitting again. You can also always reach out for help if anything is not
>    clear to you 👍🏽*
>    *Every comment with the [OPTIONAL] prefix won't stop the approval of
>    this PR. However, I strongly recommend you take them into account as they
>    can make your code better. Some of them were simply missed by the previous
>    reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/Jessekay/Portifolio/pull/2#discussion_r1068565129>:
>
> > @@ -8,33 +8,37 @@
>
>      <link href="style.css" rel="stylesheet">
>
>  </head>
>
>  <body>
>
> -    <div class="menu">
>
> -    <div class="logo">My Logo</div>
>
> -    <nav><img src="./images/ham.svg" alt=""></nav>
>
> -    </div>
>
> -    <main>
>
> +    <header class="menu">
>
>
>
>    - I think it will be better if you implement this changes suggested by
>    the previous reviewer 👇🏽
>
> [image: image]
> <https://user-images.githubusercontent.com/63473584/212165131-4c3f562f-ae8b-4577-861e-ed7ff62c6fa9.png>
> ------------------------------
>
> In index.html
> <https://github.com/Jessekay/Portifolio/pull/2#discussion_r1068566685>:
>
> > +        <div class="text"><h1> am Jesse <br>Glad to see<br> you!</h1></div>
>
> +    <div class="txt"><p>I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded, don’t hestiate to contact me.</p></div><br>
>
> +    <link class="tx">LET'S CONNECT</link><br>
>
>
>
>    - KIndly implement this changes suggested by the previous reviewer 👇🏽
>
> [image: image]
> <https://user-images.githubusercontent.com/63473584/212165354-66d0cc9a-657c-4ded-832f-58400f35d75f.png>
> ------------------------------
>
> In README.md
> <https://github.com/Jessekay/Portifolio/pull/2#discussion_r1068569492>:
>
> > +- [🔭 Future Features](#future-features)
>
> +- [🤝 Contributing](#contributing)
>
> +- [⭐️ Show your support](#support)
>
> +- [🙏 Acknowledgements](#acknowledgements)
>
> +- [❓ FAQ (OPTIONAL)](#faq)
>
> +- [📝 License](#license)
>
> +
>
> +
>
> +
>
> +# 📖 [Hello world project] <a name="about-project"></a>
>
> +
>
> +> This is my mobile version portfolio
>
> +
>
> +**[Hello world project]** is a...
>
> +
>
> +## 🛠 Built With <a name="built-with"></a>
>
>
>
>    - KIndly implement the changes suggested by the previous reviewer 👇🏽
>
> [image: image]
> <https://user-images.githubusercontent.com/63473584/212165760-bdd2f2db-3b48-4e30-b977-87379c6e6449.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Jessekay/Portifolio/pull/2#pullrequestreview-1246371432>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXSLENKHU7UPTRAJR4566DTWSBNZJANCNFSM6AAAAAATZAIQRE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-12 20:27 UTC, AbayomiOlaoye requested changes
Hi @Jessekay , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![invalid](https://user-images.githubusercontent.com/99715640/211858554-39090b6b-2f0f-45dd-b5e0-8fb805e56431.gif)

## Invalid Code Review Request

You have submitted a project, that failed linters.
- [ ] Kindly check the linters report and attempt to fix the lining errors. This check is important because it ensures that your code is according to conventional standards :wink: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-13 06:01 UTC, amejid approved these changes
Hi @Jessekay, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct use of Github flow :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 06:03 UTC, Jessekay commented
thanks

On Fri, Jan 13, 2023 at 8:01 AM Abdelmejid Oumer Ali <
***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Hi @Jessekay <https://github.com/Jessekay>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
>
> <https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966>
> Highlights
>
>    - Linter checks passing ✔️
>    - Correct use of Github flow ✔️
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Jessekay/Portifolio/pull/2#pullrequestreview-1246945536>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXSLENKDBEEH46YXKX75DJDWSDVTLANCNFSM6AAAAAATZAIQRE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-13 06:06 UTC, merged